sudo: true
os: osx
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-osx.pkg
  global:
    secure: qlQEsEu/NOwEEjWwbvbMHNuClouJI1u6x28PLzbfzRdW9qxKBPB7IcctPxFm29wzOAHg+IxFQNREXuC0fcWh/DJL7tGX4bayBInPQQbhcIXckAQKC4R7cwjXFj0BeAlUoSe8s0jMt5oACPGVdBaYAfLYMVldQnvzyw57B5SSOcehlZgivD4dJGW91Rx+iGXadGZxTnQK0ycMA+c9ZNwGxaNEZ9JbYxdgtKKb0EN+bOTH/0q07DvylPpBmHKIT/RkHimIfGBytXnEPCCpuoYfqsaFcw9HcqAviOqmpS40ukjLaGKpH8PFtPFH4vVLpdThNhW7l9Ns1BAT4nBdk3pcAzcc4E/UJUDGv50fyPzFTwluuZoU/XX2QLg6RyprsZPP+SrY9RwlTFokDNPqttzdSgoPplUhMdGVFP8dLF4TV/hAouD0WlLUZ6aokOJjARnTVgyAZtosyTtx4adMyU2v8UNprnStGHCqPPXSxOnhMQsdq4NyNXVShmzAZ5NmhKe1PbzsZoVpDE4S09S9Tl1LBiJYBoLHcpKVZ/PKpxZjX50xk5H4BU05gpH7Qa6i5cOvhvsgSNnJOjWkkQj28jDcbSkO4BIFg8oCcW2bc+RIOtW8ziTA3ekZoTQdikXZKFtGdpILtAmIXgi0S2kd+blBsCEWb/SRTrycfwAA2/xMbgQ=
before_install:
- openssl aes-256-cbc -k $SERVER_KEY_PASS -in assets/server.key.enc -out assets/server.key
  -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- curl $URL --output sfdx-osx.pkg
- sudo installer -pkg sfdx-osx.pkg -target /
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMER_KEY --jwtkeyfile assets/server.key
  --username $DEVHUB_USERNAME --setdefaultdevhubusername -a huborg
script:
- sfdx force:org:create -v huborg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human -w 10
- sfdx force:org:delete -u ciorg -p
